const path = require("path");

module.exports = {
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: "API Documentation",
      version: require(path.join(process.cwd(), "package.json")).version || "1.0.0",
      description: "API Documentation generated by Swagger",
    },
    servers: [
      { url: `http://localhost:3000` }
    ],
  },
  apis: [path.join(process.cwd(), "src", "routes", "**", "*.js")]
}