const path = require("path");

module.exports = {
  swaggerDefinition: {
    info: {
      title: "API Documentation",
      version: require(path.join(process.cwd(), "package.json")).version || "1.0.0",
      description: "API Documentation generated by Swagger",
    },
    servers: [
      { url: `http://localhost:3000` }
    ],
  }
}